/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAppRouteImport } from './routes/_app_.app'
import { Route as DocsSlugIndexRouteImport } from './routes/docs.$slug.index'
import { Route as AuthErrorIndexRouteImport } from './routes/auth.error.index'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as DocsSlugPageSlugRouteImport } from './routes/docs.$slug.$pageSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAppNewIndexRouteImport } from './routes/_app_.app.new.index'
import { Route as AppAppNewDocumentationIdStatusRouteImport } from './routes/_app_.app.new.$documentationId.status'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/_app_/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugIndexRoute = DocsSlugIndexRouteImport.update({
  id: '/docs/$slug/',
  path: '/docs/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorIndexRoute = AuthErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => AuthRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const DocsSlugPageSlugRoute = DocsSlugPageSlugRouteImport.update({
  id: '/docs/$slug/$pageSlug',
  path: '/docs/$slug/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppNewIndexRoute = AppAppNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppNewDocumentationIdStatusRoute =
  AppAppNewDocumentationIdStatusRouteImport.update({
    id: '/new/$documentationId/status',
    path: '/new/$documentationId/status',
    getParentRoute: () => AppAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof AppAppRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$slug/$pageSlug': typeof DocsSlugPageSlugRoute
  '/app/': typeof AppAppIndexRoute
  '/auth/error/': typeof AuthErrorIndexRoute
  '/docs/$slug/': typeof DocsSlugIndexRoute
  '/app/new/': typeof AppAppNewIndexRoute
  '/app/new/$documentationId/status': typeof AppAppNewDocumentationIdStatusRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAppIndexRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$slug/$pageSlug': typeof DocsSlugPageSlugRoute
  '/auth/error': typeof AuthErrorIndexRoute
  '/docs/$slug': typeof DocsSlugIndexRoute
  '/app/new': typeof AppAppNewIndexRoute
  '/app/new/$documentationId/status': typeof AppAppNewDocumentationIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app_/app': typeof AppAppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$slug/$pageSlug': typeof DocsSlugPageSlugRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/auth/error/': typeof AuthErrorIndexRoute
  '/docs/$slug/': typeof DocsSlugIndexRoute
  '/_app_/app/new/': typeof AppAppNewIndexRoute
  '/_app_/app/new/$documentationId/status': typeof AppAppNewDocumentationIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/auth/'
    | '/api/auth/$'
    | '/docs/$slug/$pageSlug'
    | '/app/'
    | '/auth/error/'
    | '/docs/$slug/'
    | '/app/new/'
    | '/app/new/$documentationId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/docs/$slug/$pageSlug'
    | '/auth/error'
    | '/docs/$slug'
    | '/app/new'
    | '/app/new/$documentationId/status'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app_/app'
    | '/_app/'
    | '/auth/'
    | '/api/auth/$'
    | '/docs/$slug/$pageSlug'
    | '/_app/app/'
    | '/auth/error/'
    | '/docs/$slug/'
    | '/_app_/app/new/'
    | '/_app_/app/new/$documentationId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AppAppRoute: typeof AppAppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DocsSlugPageSlugRoute: typeof DocsSlugPageSlugRoute
  DocsSlugIndexRoute: typeof DocsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app_/app': {
      id: '/_app_/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug/': {
      id: '/docs/$slug/'
      path: '/docs/$slug'
      fullPath: '/docs/$slug/'
      preLoaderRoute: typeof DocsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error/': {
      id: '/auth/error/'
      path: '/error'
      fullPath: '/auth/error/'
      preLoaderRoute: typeof AuthErrorIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/$slug/$pageSlug': {
      id: '/docs/$slug/$pageSlug'
      path: '/docs/$slug/$pageSlug'
      fullPath: '/docs/$slug/$pageSlug'
      preLoaderRoute: typeof DocsSlugPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app_/app/new/': {
      id: '/_app_/app/new/'
      path: '/new'
      fullPath: '/app/new/'
      preLoaderRoute: typeof AppAppNewIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app_/app/new/$documentationId/status': {
      id: '/_app_/app/new/$documentationId/status'
      path: '/new/$documentationId/status'
      fullPath: '/app/new/$documentationId/status'
      preLoaderRoute: typeof AppAppNewDocumentationIdStatusRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthErrorIndexRoute: typeof AuthErrorIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthErrorIndexRoute: AuthErrorIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppAppRouteChildren {
  AppAppNewIndexRoute: typeof AppAppNewIndexRoute
  AppAppNewDocumentationIdStatusRoute: typeof AppAppNewDocumentationIdStatusRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppNewIndexRoute: AppAppNewIndexRoute,
  AppAppNewDocumentationIdStatusRoute: AppAppNewDocumentationIdStatusRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AppAppRoute: AppAppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DocsSlugPageSlugRoute: DocsSlugPageSlugRoute,
  DocsSlugIndexRoute: DocsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
